<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net9.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TyreLifecycle.Application.Contracts\TyreLifecycle.Application.Contracts.csproj" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="9.2.1" />
  </ItemGroup>
</Project>
